language: android
jdk: oraclejdk8
dist: trusty
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - tools
    - android-27
    - android-24
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24
    - sys-img-armeabi-v7a-android-25

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    -
before_install:
  - yes | sdkmanager "platforms;android-28"
  -

script:
  ./gradlew assembleRelease